//! Ed25519 key gen/load — PEM PKCS8 (private) / SPKI (public), the same
//! encodings `cryptography.hazmat.primitives.serialization` produces on the
//! Python side (`capsule_sidecar.load_or_create_signing_key`), so a keypair
//! generated by either language loads cleanly in the other.

use ed25519_dalek::pkcs8::spki::der::pem::LineEnding;
use ed25519_dalek::pkcs8::{DecodePrivateKey, DecodePublicKey, EncodePrivateKey, EncodePublicKey};
use ed25519_dalek::{SigningKey, VerifyingKey};
use rand_core::OsRng;

pub struct KeyPair {
    pub signing_key: SigningKey,
}

impl KeyPair {
    pub fn generate() -> Self {
        Self {
            signing_key: SigningKey::generate(&mut OsRng),
        }
    }

    pub fn verifying_key(&self) -> VerifyingKey {
        self.signing_key.verifying_key()
    }

    /// PKCS8 PEM, matching `serialization.PrivateFormat.PKCS8` /
    /// `Encoding.PEM` with no encryption on the Python side.
    pub fn private_key_pem(&self) -> String {
        self.signing_key
            .to_pkcs8_pem(LineEnding::LF)
            .expect("PKCS8 PEM encode")
            .to_string()
    }

    /// SubjectPublicKeyInfo PEM, matching
    /// `serialization.PublicFormat.SubjectPublicKeyInfo` on the Python side.
    pub fn public_key_pem(&self) -> String {
        self.verifying_key()
            .to_public_key_pem(LineEnding::LF)
            .expect("SPKI PEM encode")
    }
}

pub fn load_signing_key_pem(pem: &str) -> anyhow::Result<SigningKey> {
    Ok(SigningKey::from_pkcs8_pem(pem)?)
}

pub fn load_verifying_key_pem(pem: &str) -> anyhow::Result<VerifyingKey> {
    Ok(VerifyingKey::from_public_key_pem(pem)?)
}
