//! Ed25519 key gen/load/persist/rotate — PEM PKCS8 (private) / SPKI (public),
//! the same encodings `cryptography.hazmat.primitives.serialization`
//! produces on the Python side (`capsule_sidecar.load_or_create_signing_key`),
//! so a keypair generated by either language loads cleanly in the other.
//!
//! Persistence and rotation follow the two existing precedents rather than
//! inventing a new shape:
//! - `capsule_sidecar.load_or_create_signing_key`: `<keys_dir>/node-key.pem`
//!   generated on first run, written 0600, public half beside it, never
//!   committed.
//! - `capsule_ledger`'s rotation-as-ledger-event pattern (no rotation policy
//!   exists on the Python producer side yet, per the Milestone 1 report):
//!   a rotation is a plain key swap here, returning a `RotationRecord` the
//!   caller appends to the ledger as an ordinary capsule so the transition is
//!   itself part of the durable, chained record rather than a side channel.

use ed25519_dalek::pkcs8::spki::der::pem::LineEnding;
use ed25519_dalek::pkcs8::{DecodePrivateKey, DecodePublicKey, EncodePrivateKey, EncodePublicKey};
use ed25519_dalek::{SigningKey, VerifyingKey};
use rand_core::OsRng;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

const NODE_KEY_FILENAME: &str = "node-key.pem";
const NODE_PUBKEY_FILENAME: &str = "node-key.pub.pem";
const ARCHIVE_DIRNAME: &str = "archive";

#[derive(Debug, thiserror::Error)]
pub enum KeyError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("key decode error: {0}")]
    Decode(#[from] anyhow::Error),
    #[error("no current key at {0}; cannot rotate a key that does not exist yet")]
    NoCurrentKey(String),
}

#[derive(Debug)]
pub struct KeyPair {
    pub signing_key: SigningKey,
}

impl KeyPair {
    pub fn generate() -> Self {
        Self {
            signing_key: SigningKey::generate(&mut OsRng),
        }
    }

    pub fn verifying_key(&self) -> VerifyingKey {
        self.signing_key.verifying_key()
    }

    /// PKCS8 PEM, matching `serialization.PrivateFormat.PKCS8` /
    /// `Encoding.PEM` with no encryption on the Python side.
    pub fn private_key_pem(&self) -> String {
        self.signing_key
            .to_pkcs8_pem(LineEnding::LF)
            .expect("PKCS8 PEM encode")
            .to_string()
    }

    /// SubjectPublicKeyInfo PEM, matching
    /// `serialization.PublicFormat.SubjectPublicKeyInfo` on the Python side.
    pub fn public_key_pem(&self) -> String {
        self.verifying_key()
            .to_public_key_pem(LineEnding::LF)
            .expect("SPKI PEM encode")
    }

    /// Stable key identifier: first 16 hex chars of SHA-256 over the raw
    /// 32-byte public key -- the same scheme `capsule-anchor`'s
    /// `GET /anchor/authority-pubkey` uses for its own `key_id`, reused here
    /// so a key_id computed by either side of this system means the same
    /// thing.
    pub fn key_id(&self) -> String {
        key_id_of(&self.verifying_key())
    }
}

pub fn key_id_of(vk: &VerifyingKey) -> String {
    let digest = Sha256::digest(vk.as_bytes());
    hex::encode(&digest[..8])
}

pub fn load_signing_key_pem(pem: &str) -> anyhow::Result<SigningKey> {
    Ok(SigningKey::from_pkcs8_pem(pem)?)
}

pub fn load_verifying_key_pem(pem: &str) -> anyhow::Result<VerifyingKey> {
    Ok(VerifyingKey::from_public_key_pem(pem)?)
}

#[cfg(unix)]
fn write_private_pem(path: &Path, pem: &str) -> std::io::Result<()> {
    fs::write(path, pem)?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
}

#[cfg(not(unix))]
fn write_private_pem(path: &Path, pem: &str) -> std::io::Result<()> {
    fs::write(path, pem)
}

/// Load `<keys_dir>/node-key.pem` if present; otherwise generate a fresh
/// Ed25519 key, write it 0600, write the public half beside it as
/// `node-key.pub.pem`, and return it. Mirrors
/// `capsule_sidecar.load_or_create_signing_key` exactly (including: never
/// overwrite an existing key, keys_dir created if absent).
pub fn load_or_create(keys_dir: &Path) -> Result<KeyPair, KeyError> {
    fs::create_dir_all(keys_dir)?;
    let node_key_path = keys_dir.join(NODE_KEY_FILENAME);
    if node_key_path.exists() {
        let pem = fs::read_to_string(&node_key_path)?;
        let signing_key = load_signing_key_pem(&pem).map_err(KeyError::Decode)?;
        return Ok(KeyPair { signing_key });
    }
    let keys = KeyPair::generate();
    write_private_pem(&node_key_path, &keys.private_key_pem())?;
    fs::write(keys_dir.join(NODE_PUBKEY_FILENAME), keys.public_key_pem())?;
    Ok(keys)
}

/// Rotation record for a key transition -- the caller appends this into the
/// ledger as an ordinary (chained) capsule so the transition is part of the
/// durable, verifiable record rather than tracked out-of-band. Mirrors
/// `capsule_ledger`'s `key_rotation` event shape (`old_key_id`, `new_key_id`,
/// `rotated_at`).
#[derive(Debug)]
pub struct RotationRecord {
    pub old_key_id: String,
    pub new_key_id: String,
    pub rotated_at: String,
    pub new_keys: KeyPair,
}

/// Rotate the active signing key at `keys_dir`: the current `node-key.pem`
/// (and its public half) are moved into `<keys_dir>/archive/` under
/// filenames keyed by their `key_id` -- so a verifier checking a capsule
/// signed before this rotation can still recover the exact public key that
/// signed it -- and a freshly generated key becomes the new
/// `node-key.pem`/`node-key.pub.pem`.
///
/// Errors if there is no current key to rotate away from: rotation is a
/// transition between two keys, not key creation (use `load_or_create` for
/// the first key).
pub fn rotate(keys_dir: &Path) -> Result<RotationRecord, KeyError> {
    let node_key_path = keys_dir.join(NODE_KEY_FILENAME);
    let node_pub_path = keys_dir.join(NODE_PUBKEY_FILENAME);
    if !node_key_path.exists() {
        return Err(KeyError::NoCurrentKey(node_key_path.display().to_string()));
    }
    let old_pem = fs::read_to_string(&node_key_path)?;
    let old_signing_key = load_signing_key_pem(&old_pem).map_err(KeyError::Decode)?;
    let old_key_id = key_id_of(&old_signing_key.verifying_key());

    let archive_dir = keys_dir.join(ARCHIVE_DIRNAME);
    fs::create_dir_all(&archive_dir)?;
    let archived_priv: PathBuf = archive_dir.join(format!("node-key.{old_key_id}.pem"));
    let archived_pub: PathBuf = archive_dir.join(format!("node-key.{old_key_id}.pub.pem"));
    fs::rename(&node_key_path, &archived_priv)?;
    #[cfg(unix)]
    fs::set_permissions(&archived_priv, fs::Permissions::from_mode(0o600))?;
    if node_pub_path.exists() {
        fs::rename(&node_pub_path, &archived_pub)?;
    }

    let new_keys = KeyPair::generate();
    let new_key_id = new_keys.key_id();
    write_private_pem(&node_key_path, &new_keys.private_key_pem())?;
    fs::write(&node_pub_path, new_keys.public_key_pem())?;

    let rotated_at = crate::timestamp::utc_now_iso8601();

    Ok(RotationRecord {
        old_key_id,
        new_key_id,
        rotated_at,
        new_keys,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_or_create_generates_once_then_persists() {
        let dir = tempfile::tempdir().unwrap();
        let k1 = load_or_create(dir.path()).unwrap();
        let id1 = k1.key_id();

        // Second call must load the SAME key, not generate a new one.
        let k2 = load_or_create(dir.path()).unwrap();
        assert_eq!(id1, k2.key_id());
        assert_eq!(k1.public_key_pem(), k2.public_key_pem());

        assert!(dir.path().join(NODE_KEY_FILENAME).exists());
        assert!(dir.path().join(NODE_PUBKEY_FILENAME).exists());
    }

    #[cfg(unix)]
    #[test]
    fn private_key_file_is_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        load_or_create(dir.path()).unwrap();
        let mode = fs::metadata(dir.path().join(NODE_KEY_FILENAME))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600);
    }

    #[test]
    fn key_id_is_stable_and_distinguishes_keys() {
        let k1 = KeyPair::generate();
        let k2 = KeyPair::generate();
        assert_eq!(k1.key_id(), key_id_of(&k1.verifying_key()));
        assert_ne!(k1.key_id(), k2.key_id());
        assert_eq!(k1.key_id().len(), 16); // 8 bytes hex-encoded
    }

    #[test]
    fn rotate_requires_an_existing_key() {
        let dir = tempfile::tempdir().unwrap();
        let err = rotate(dir.path()).unwrap_err();
        assert!(matches!(err, KeyError::NoCurrentKey(_)));
    }

    #[test]
    fn rotate_archives_old_key_and_activates_new_one() {
        let dir = tempfile::tempdir().unwrap();
        let original = load_or_create(dir.path()).unwrap();
        let original_id = original.key_id();

        let record = rotate(dir.path()).unwrap();
        assert_eq!(record.old_key_id, original_id);
        assert_ne!(record.new_key_id, record.old_key_id);
        assert_eq!(record.new_key_id, record.new_keys.key_id());

        // The now-active key is the new one, not the old.
        let active = load_or_create(dir.path()).unwrap();
        assert_eq!(active.key_id(), record.new_key_id);

        // The old key's PUBLIC half is still recoverable for verifying
        // capsules it signed before the rotation (key-transition handling).
        let archived_pub = dir
            .path()
            .join(ARCHIVE_DIRNAME)
            .join(format!("node-key.{original_id}.pub.pem"));
        assert!(archived_pub.exists());
        let recovered = load_verifying_key_pem(&fs::read_to_string(&archived_pub).unwrap())
            .unwrap();
        assert_eq!(key_id_of(&recovered), original_id);
        assert_eq!(recovered, original.verifying_key());
    }

    #[test]
    fn capsule_signed_before_rotation_still_verifies_with_archived_key() {
        // The point of key-transition handling: rotating the ACTIVE key must
        // never invalidate a signature already produced by the OLD key.
        use ed25519_dalek::Signer;
        let dir = tempfile::tempdir().unwrap();
        let original = load_or_create(dir.path()).unwrap();
        let message = b"payload signed before rotation";
        let sig = original.signing_key.sign(message);

        rotate(dir.path()).unwrap();

        let archived_pub = dir
            .path()
            .join(ARCHIVE_DIRNAME)
            .join(format!("node-key.{}.pub.pem", original.key_id()));
        let recovered = load_verifying_key_pem(&fs::read_to_string(&archived_pub).unwrap())
            .unwrap();
        recovered.verify_strict(message, &sig).expect(
            "a signature made before rotation must still verify with the archived old key",
        );
    }
}
