//! The Rust split-stage code over the fixtures the Python reference also
//! runs (`tests/fixtures/split-stage/`, regenerated by `generate.py` there).
//! Every expected verdict in those files is hand-written from the design;
//! neither implementation computes them.

use capsule_producer::stage::{CoordinatorReceipt, FrameFold, Lane, LaneFold, StageBlock};
use capsule_producer::stage_verify::{verify_split, CarriedStageRecord};
use serde_json::Value;

fn fixture(name: &str) -> Vec<Value> {
    let raw = match name {
        "fold" => include_str!("../../../tests/fixtures/split-stage/fold-vectors.json"),
        "block" => include_str!("../../../tests/fixtures/split-stage/block-cases.json"),
        "receipt" => include_str!("../../../tests/fixtures/split-stage/receipt-cases.json"),
        "hop" => include_str!("../../../tests/fixtures/split-stage/hop-cases.json"),
        other => panic!("no fixture {other}"),
    };
    serde_json::from_str::<Value>(raw).unwrap().as_array().unwrap().clone()
}

fn lane(wire: &str) -> Lane {
    match wire {
        "forward" => Lane::Forward,
        "reply" => Lane::Reply,
        "direct_return" => Lane::DirectReturn,
        other => panic!("unknown lane {other}"),
    }
}

#[test]
fn fold_matches_the_python_reference_byte_for_byte() {
    let cases = fixture("fold");
    assert!(!cases.is_empty());
    for case in cases {
        let mut fold = FrameFold::new(
            b"",
            case["coordinator_node_id"].as_str().unwrap(),
            case["run_id"].as_str().unwrap(),
            case["request_id"].as_str().unwrap().parse().unwrap(),
            u32::try_from(case["hop_index"].as_u64().unwrap()).unwrap(),
            lane(case["lane"].as_str().unwrap()),
        );
        for frame in case["frames_hex"].as_array().unwrap() {
            fold.push(&hex::decode(frame.as_str().unwrap()).unwrap());
        }
        let want: LaneFold = serde_json::from_value(case["expect"].clone()).unwrap();
        assert_eq!(fold.finish(), want, "{}", case["name"]);
    }
}

#[test]
fn block_rules_agree_with_the_python_reference() {
    let cases = fixture("block");
    assert!(cases.len() > 20);
    for case in cases {
        let got = StageBlock::from_value(&case["block"]);
        assert_eq!(
            got.is_ok(),
            case["valid"].as_bool().unwrap(),
            "{}: {:?}",
            case["name"],
            got.err()
        );
    }
}

#[test]
fn receipt_rules_agree_with_the_python_reference() {
    let cases = fixture("receipt");
    assert!(cases.len() > 10);
    for case in cases {
        let got = CoordinatorReceipt::from_value(&case["receipt"]);
        assert_eq!(
            got.is_ok(),
            case["valid"].as_bool().unwrap(),
            "{}: {:?}",
            case["name"],
            got.err()
        );
    }
}

#[test]
fn hop_check_agrees_with_the_hand_written_verdicts() {
    let cases = fixture("hop");
    assert!(cases.len() > 10);
    for case in cases {
        let own = StageBlock::from_value(&case["own"]).unwrap();
        let receipt = CoordinatorReceipt::from_value(&case["receipt"]).unwrap();
        let carried: Vec<CarriedStageRecord> = case["carried"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| CarriedStageRecord {
                capsule_id: c["capsule_id"].as_str().unwrap().to_string(),
                block: c["block"].clone(),
            })
            .collect();
        let verdict = verify_split(&own, &receipt, &carried).unwrap();
        assert_eq!(
            serde_json::to_value(&verdict).unwrap(),
            case["expect"],
            "{}",
            case["name"]
        );
    }
}
